before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh

script: "./travis/build.sh"

after_success:
- "./travis/publish.sh"

env:
  global:
  - GH_USER_NAME: livioso
  - GH_PROJECT_NAME: pandoc-travis-setup
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`/$TRAVIS_REPO_SLUG
  - RESULT_PDF_PATH=$CI_HOME/thesis.pdf
  - TZ="Europe/Zurich"
