before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y texlive-core texlive-xetex
  - chmod u+x ./travis/build.sh
  - chmod u+x ./travis/publish.sh

script: ./travis/build.sh

after_success:
    - ./travis/publish.sh

#
# Environment Variables:
# Customize to your needs.
#
# Thanks to @pwmckenna (https://github.com/pwmckenna/todium/blob/master/.travis.yml)
# for the example how files can be pushed to gh-pages branch safely.
#
env:
    global:
        # GH_OAUTH_TOKEN is the oauth token generated as described at
        # https://help.github.com/articles/creating-an-oauth-token-for-command-line-use
        #
        # curl -u 'username' -d '{"scopes":["repo"],"note":"push to gh-pages from travis"}' https://api.github.com/authorizations
        #
        # It must be encrypted using the travis gem
        # http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
        #
        # travis encrypt GH_OAUTH_TOKEN=b2797fff05e7461c4c8174fae08fb006cbadba9f
        #
        # Copy the resulting "secure" property here:
        - secure: "JcwhYrVpo+d2opwuwivo6vrt3/a5uRNTzCrnjsr4VgDU/e/VS7eIe2tgdfnVtuei0uca7UEv55IMeHJHacD+lzFTHOtz0QDYs/TrEd1Vl1AlZTdsZDgR1bMWRN9dV+O7nFU1lS5irK7U7UmchKE/BeFc5idohbuvCvBVLJzA3/Rx1dVrjnQo1jptRAYUb2JJAwBXNpZb+/gkXGLVsud3DQvdtMsA/1gTq3Tu2O6oIT0vTqkiIaj0BVVc7cTnZny2ZBhzY3JRrYW2coowjwYDsrU0XDp3+9SMTaOUTDJ62h8wad2sx/CJEtUMxOJtWqi91ZLcrccxgChxesixD+pY/30y9uuml11a5Tp/WvISo509x26g7TUbICYdBiTrqlupdp6a2rF2DSVvl3EpkDwWeV2iQ+gffcgjtB320G0t8DNw6/fLOCaOBzOJQxHQ7qgBNJpZmdM6P8rKwOn9OCcm2jM9zLD+ZybW+BA9X+lg35vGOSQShnuNvsZhL1mArB8Lf6G7cD5sKzrB9D34N0IFWuz0s0jHxSOyPHWbsPeTHTMep8BNGcAmDTaz3vsxN6cDEa2giUr0CTHhSNTrAuTe5ihn8WwmqxZBTdqYk6zDmg/lIcrnMH9qMsb6MS39o8wOA3ZDveY8m7vzFbaD2GgEt4qi0UGhwNPm3b+nzPwBgaw="

        # GH_USER_NAME & GH_PROJECT_NAME
        # The Github Account you created the OAuth token with and the repo you
        # want to push the generated PDF to (gh-pages branch is used automatically)
        - GH_USER_NAME: livioso
        - GH_PROJECT_NAME: pandoc-travis-setup

        # GIT_AUTHOR_NAME & GIT_AUTHOR_EMAIL
        # When pushing to the gh-pages branch, these informtion are used to
        # perform the git commit
        - GIT_AUTHOR_NAME: "Travis"
        - GIT_AUTHOR_EMAIL: "noreply@travis-ci.org"

        # CI_HOME
        # A shortcut to the directory where travis cloned the actual git repo
        - CI_HOME=`pwd`/$TRAVIS_REPO_SLUG

        # RESULT_PDF_PATH
        # A shortcut to the built PDF document
        - RESULT_PDF_PATH=$CI_HOME/thesis.pdf

        # TZ
        # Timezone
        - TZ="Europe/Zurich"

